# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 23f3a22a1704189d2ef3bacfc249e7cbdb917a8775328ecaf9aab8add899473954613dca1f1fbfcd347673c2fe3c09785f619341c01bb8005a6cb3314af47bd2

test:
  secret_key_base: f4320a30b37a3971f9db6d4eeaa88eefa956b1ef7645b8cc2f5b936f03b952837d4809b760bfb172c361ce7f95c8f1885d785f1ccf967b18a5fd81b293fb9ee4

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
